# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
      - main
      - development

resources:
  repositories:
    # Azure DevOps repository
    - repository: pelikirja-pipelines
      type: git
      # project/repository
      name: pelikirja/pelikirja-pipelines

pool:
  vmImage: ubuntu-latest

extends:
  template: azure-pipelines.yaml@pelikirja-pipelines
